blank_issues_enabled: true
contact_links:
  - name: Usage questions and ideas
    url: https://github.com/KaramTNC/dotnet-quality-enforcer/discussions
    about: Ask questions or compare approaches with other users.
